sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 92978
mybatis:
  configuration:
    map-underscore-to-camel-case: true